# Generated by Django 5.0.3 on 2024-03-25 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_title', models.CharField(db_index=True, max_length=30, verbose_name='Категория')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Article category',
                'verbose_name_plural': 'Article categories',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_title', models.CharField(help_text='Тут добавьте Тэг', max_length=30, verbose_name='Тэг')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
            },
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(help_text='Тут добавьте название статьи', max_length=100, verbose_name='Название статьи')),
                ('article_news', models.TextField(verbose_name='Статья')),
                ('article_image', models.FileField(upload_to='article_images', verbose_name='Изображение')),
                ('article_author', models.CharField(help_text='ФИО автора', max_length=50, verbose_name='Автор')),
                ('article_created_at', models.DateTimeField(auto_now_add=True)),
                ('article_categories', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='articles.categorymodel', verbose_name='Article categories')),
                ('article_tags', models.ManyToManyField(default='', to='articles.tagmodel', verbose_name='Tag')),
            ],
            options={
                'verbose_name': 'News article',
                'verbose_name_plural': 'News articles',
            },
        ),
    ]
